### ISSUE TITLE
Missing necessary files model.py and bleu.py?

### ISSUE THREAD

**Issue by nutor** [Chenning-Tao/C4#1]
Hi. I'm quite interested in your work and was trying to replicate the experiments with the released code, but something goes wrong :( 

The script announces that `model` and `bleu` are not found. It seems that the necesarry files `model.py` and `bleu.py` are missing? Could you please supplement these two files (and any other files necessary yet missing)? 

Btw, can you also tell the necessary python libraries and their versions to run the released codes? 

Thx a lot.

**Comment by Chenning-Tao** [comment]
I'v updated the missing files and library

**Comment by nutor** [comment]
> I'v updated the missing files and library

Great! Thx. It works now.
